import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('vi'),
    Locale('zh'),
    Locale('ja'),
  ];
  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  String t(String key, [Map<String, Object> args = const {}]) {
    var value =
        (_translations[locale.languageCode] ?? _translations['en']!)[key] ??
            _translations['en']![key] ??
            key;
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return value;
  }

  String profileField(String key) => t('field.$key');
  String themeName(String value) => t('theme.$value');
  String languageName(String value) =>
      const {
        'en': 'English',
        'vi': 'Tiếng Việt',
        'zh': '中文',
        'ja': '日本語',
      }[value] ??
      value;
  String languageFlag(String value) =>
      const {
        'en': '🇬🇧',
        'vi': '🇻🇳',
        'zh': '🇨🇳',
        'ja': '🇯🇵',
      }[value] ??
      '🌐';
  String languageDisplayName(String value) =>
      '${languageFlag(value)}  ${languageName(value)}';
  String defaultProfileName(String value) => switch (value) {
        'Family' => t('defaultProfile.family'),
        'Friends' => t('defaultProfile.friends'),
        'Work' => t('defaultProfile.work'),
        'Public' => t('defaultProfile.public'),
        _ => value,
      };
}

Locale detectDefaultLocale(List<Locale> preferredLocales,
    {String? countryCode}) {
  final detectedCountry = countryCode?.toUpperCase();
  if (detectedCountry == 'VN') return const Locale('vi');
  if (const {'CN', 'TW', 'HK', 'MO'}.contains(detectedCountry)) {
    return const Locale('zh');
  }
  if (detectedCountry == 'JP') return const Locale('ja');
  if (preferredLocales.isEmpty) return const Locale('en');
  final locale = preferredLocales.first;
  final language = locale.languageCode.toLowerCase();
  final country = locale.countryCode?.toUpperCase();
  if (language == 'vi' || country == 'VN') return const Locale('vi');
  if (language == 'zh' || const {'CN', 'TW', 'HK', 'MO'}.contains(country)) {
    return const Locale('zh');
  }
  if (language == 'ja' || country == 'JP') return const Locale('ja');
  return const Locale('en');
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const _translations = <String, Map<String, String>>{
  'en': {
    'tagline': 'Your contacts. Your keys.',
    'username': 'Username',
    'usernameHint': '3–32 characters: letters, numbers, . or _',
    'legacyLoginHint': 'Existing accounts may temporarily use email',
    'recoveryEmail': 'Recovery email',
    'recoveryEmailHint': 'Only used if you forget your password',
    'passwordMin': 'Password (10+ characters)',
    'reenterPassword': 'Re-enter password',
    'createAccount': 'Create account',
    'accountCreatedSignIn': 'Account created. Sign in to continue.',
    'signIn': 'Sign in',
    'forgotPassword': 'Forgot password?',
    'alreadyHaveAccount': 'Already have an account?',
    'createAnAccount': 'Create an account',
    'resetToken': 'Reset token',
    'newPassword': 'New password',
    'cancel': 'Cancel',
    'continue': 'Continue',
    'save': 'Save',
    'delete': 'Delete',
    'change': 'Change',
    'import': 'Import',
    'profile': 'Profile',
    'contacts': 'Contacts',
    'connections': 'Connections',
    'qr': 'QR',
    'myQr': 'My QR',
    'settings': 'Settings',
    'scan': 'Scan',
    'searchContacts': 'Search name, nickname, or company',
    'noContacts': 'No contacts found. Scan a NexBook QR to connect.',
    'privateContact': 'Private contact',
    'connectionRequest': 'Connection request · {id}',
    'incomingRequests': 'Incoming requests',
    'sentRequests': 'Sent requests',
    'incomingRequest': 'Wants to connect with you',
    'sentRequest': 'Waiting for a response',
    'noConnectionRequests': 'No pending connection requests.',
    'accept': 'Accept',
    'reject': 'Reject',
    'cancelRequest': 'Cancel request',
    'changeSharingProfile': 'Change sharing profile',
    'disable': 'Disable',
    'enable': 'Enable',
    'offlineCacheUnavailable': 'Offline cache unavailable.',
    'shareWhichProfile': 'Share which profile?',
    'myProfile': 'My profile',
    'syncNow': 'Sync now',
    'addYourDetails': 'Add your details',
    'fieldsSaved': '{count} fields saved locally',
    'sharingProfiles': 'Sharing profiles',
    'sharingProfilesHint':
        'Each profile is encrypted independently. Only selected fields are included.',
    'visibleFieldsVersion': '{count} visible fields · v{version}',
    'duplicate': 'Duplicate',
    'copySuffix': '{name} copy',
    'profilesSynced': 'Encrypted profiles synced.',
    'syncQueued': 'Sync will retry when the connection is available.',
    'masterProfile': 'Master profile',
    'saveLocally': 'Save locally',
    'newSharingProfile': 'New sharing profile',
    'editSharingProfile': 'Edit sharing profile',
    'name': 'Name',
    'scanQr': 'Scan NexBook QR',
    'saveQr': 'Save QR',
    'shareQr': 'Share QR',
    'uploadQrImage': 'Choose QR image',
    'toggleFlash': 'Toggle flashlight',
    'switchCamera': 'Switch camera',
    'qrSaved': 'QR image saved.',
    'qrNotFound': 'No NexBook QR was found in this image.',
    'connectionQueued': 'Connection request saved and ready to sync.',
    'shareQrLink': 'Share QR link',
    'shareQrSubject': 'Connect with me on NexBook',
    'cannotLoadQr': 'Cannot load your QR code.',
    'account': 'Account',
    'couldNotLoadAccount': 'Could not load account information.',
    'preferences': 'Preferences',
    'notifications': 'Notifications',
    'notificationsHint': 'Connection and profile update alerts',
    'automaticSync': 'Automatic sync',
    'automaticSyncHint': 'Sync encrypted changes when online',
    'theme': 'Theme',
    'language': 'Language',
    'yourData': 'Your data',
    'exportBackup': 'Export backup',
    'exportBackupHint': 'Master profile and settings as JSON',
    'importBackup': 'Import backup',
    'importBackupHint': 'Restore from NexBook JSON',
    'changePassword': 'Change password',
    'signOut': 'Sign out',
    'deleteAccount': 'Delete account',
    'privacyNotice':
        'Profile content is encrypted on this device before upload. NexBook servers cannot read it.',
    'backupSubject': 'NexBook encrypted-device backup',
    'pasteBackupJson': 'Paste backup JSON',
    'invalidBackup': 'This backup file is invalid or unsupported.',
    'deleteAccountQuestion': 'Delete account permanently?',
    'deleteAccountWarning':
        'Your account, connections, encrypted blobs, device keys, and local data will be removed. This cannot be undone.',
    'currentPassword': 'Current password',
    'newPasswordMin': 'New password (10+ characters)',
    'changeRecoveryEmail': 'Change recovery email',
    'recoveryEmailUpdated': 'Recovery email has been updated.',
    'theme.system': 'System',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'language.en': 'English',
    'language.vi': 'Vietnamese',
    'language.zh': 'Chinese',
    'language.ja': 'Japanese',
    'defaultProfile.family': 'Family',
    'defaultProfile.friends': 'Friends',
    'defaultProfile.work': 'Work',
    'defaultProfile.public': 'Public',
    'field.fullName': 'Full name',
    'field.nickname': 'Nickname',
    'field.birthday': 'Birthday',
    'field.gender': 'Gender',
    'field.company': 'Company',
    'field.position': 'Position',
    'field.phone': 'Phone',
    'field.email': 'Email',
    'field.address': 'Address',
    'field.website': 'Website',
    'field.facebook': 'Facebook',
    'field.instagram': 'Instagram',
    'field.linkedIn': 'LinkedIn',
    'field.telegram': 'Telegram',
    'field.whatsApp': 'WhatsApp',
    'field.weChat': 'WeChat',
    'field.zalo': 'Zalo',
    'field.github': 'GitHub',
    'field.notes': 'Notes',
    'error.passwordMismatch': 'The passwords do not match.',
    'error.weakPassword': 'Password must contain at least 10 characters.',
    'error.invalidUsername':
        'Username must be 3–32 characters and use only letters, numbers, dots, or underscores.',
    'error.invalidEmail': 'Enter a valid recovery email address.',
    'error.usernameRequired': 'Enter your username.',
    'error.usernameExists': 'This username is already taken.',
    'error.recoveryEmailExists':
        'This recovery email is already linked to another account.',
    'error.invalidCredentials': 'Username or password is incorrect.',
    'error.invalidPassword': 'Current password is incorrect.',
    'error.invalidToken': 'The reset token is invalid or has expired.',
    'error.accountDisabled': 'This account has been disabled.',
    'error.unauthorized': 'Your session has expired. Please sign in again.',
    'error.connectionExists':
        'You are already connected to this person or have a pending request.',
    'error.invalidPeer': 'You cannot connect to your own account.',
    'error.invalidProfileSet':
        'This sharing profile is unavailable. Sync and try again.',
    'error.invalidState': 'This action is not available in the current state.',
    'error.forbidden': 'You do not have permission to perform this action.',
    'error.versionConflict': 'This data changed elsewhere. Sync and try again.',
    'error.rateLimited':
        'Too many requests. Please wait a moment and try again.',
    'error.network':
        'Cannot connect to NexBook. Check your internet connection and try again.',
    'error.timeout': 'The request took too long. Please try again.',
    'error.server':
        'NexBook is temporarily unavailable. Please try again later.',
    'error.generic': 'Something went wrong. Please try again.',
  },
  'vi': {
    'tagline': 'Danh bạ của bạn. Chìa khóa của bạn.',
    'username': 'Tên đăng nhập',
    'usernameHint': '3–32 ký tự: chữ, số, dấu chấm hoặc gạch dưới',
    'legacyLoginHint': 'Tài khoản cũ có thể tạm dùng email để đăng nhập',
    'recoveryEmail': 'Email khôi phục',
    'recoveryEmailHint': 'Chỉ dùng khi bạn quên mật khẩu',
    'passwordMin': 'Mật khẩu (từ 10 ký tự)',
    'reenterPassword': 'Nhập lại mật khẩu',
    'createAccount': 'Tạo tài khoản',
    'accountCreatedSignIn': 'Đã tạo tài khoản. Hãy đăng nhập để tiếp tục.',
    'signIn': 'Đăng nhập',
    'forgotPassword': 'Quên mật khẩu?',
    'alreadyHaveAccount': 'Đã có tài khoản?',
    'createAnAccount': 'Tạo tài khoản mới',
    'resetToken': 'Mã đặt lại mật khẩu',
    'newPassword': 'Mật khẩu mới',
    'cancel': 'Hủy',
    'continue': 'Tiếp tục',
    'save': 'Lưu',
    'delete': 'Xóa',
    'change': 'Đổi',
    'import': 'Nhập',
    'profile': 'Hồ sơ',
    'contacts': 'Danh bạ',
    'connections': 'Kết nối',
    'qr': 'QR',
    'myQr': 'QR của tôi',
    'settings': 'Cài đặt',
    'scan': 'Quét mã',
    'searchContacts': 'Tìm tên, biệt danh hoặc công ty',
    'noContacts': 'Chưa có liên hệ. Quét mã QR NexBook để kết nối.',
    'privateContact': 'Liên hệ riêng tư',
    'connectionRequest': 'Yêu cầu kết nối · {id}',
    'incomingRequests': 'Yêu cầu đến',
    'sentRequests': 'Đã gửi',
    'incomingRequest': 'Muốn kết nối với bạn',
    'sentRequest': 'Đang chờ phản hồi',
    'noConnectionRequests': 'Không có yêu cầu kết nối đang chờ.',
    'accept': 'Chấp nhận',
    'reject': 'Từ chối',
    'cancelRequest': 'Hủy yêu cầu',
    'changeSharingProfile': 'Đổi hồ sơ chia sẻ',
    'disable': 'Tắt kết nối',
    'enable': 'Bật kết nối',
    'offlineCacheUnavailable': 'Không thể đọc dữ liệu ngoại tuyến.',
    'shareWhichProfile': 'Chia sẻ hồ sơ nào?',
    'myProfile': 'Hồ sơ của tôi',
    'syncNow': 'Đồng bộ ngay',
    'addYourDetails': 'Thêm thông tin của bạn',
    'fieldsSaved': 'Đã lưu {count} trường trên thiết bị',
    'sharingProfiles': 'Hồ sơ chia sẻ',
    'sharingProfilesHint':
        'Mỗi hồ sơ được mã hóa riêng. Chỉ các trường được chọn mới được chia sẻ.',
    'visibleFieldsVersion': '{count} trường hiển thị · phiên bản {version}',
    'duplicate': 'Nhân bản',
    'copySuffix': 'Bản sao {name}',
    'profilesSynced': 'Đã đồng bộ hồ sơ mã hóa.',
    'syncQueued': 'Sẽ đồng bộ lại khi có kết nối mạng.',
    'masterProfile': 'Hồ sơ chính',
    'saveLocally': 'Lưu trên thiết bị',
    'newSharingProfile': 'Tạo hồ sơ chia sẻ',
    'editSharingProfile': 'Sửa hồ sơ chia sẻ',
    'name': 'Tên',
    'scanQr': 'Quét mã QR NexBook',
    'saveQr': 'Lưu QR',
    'shareQr': 'Chia sẻ QR',
    'uploadQrImage': 'Chọn ảnh QR',
    'toggleFlash': 'Bật hoặc tắt đèn pin',
    'switchCamera': 'Đổi camera',
    'qrSaved': 'Đã lưu ảnh QR.',
    'qrNotFound': 'Không tìm thấy mã QR NexBook trong ảnh này.',
    'connectionQueued': 'Đã lưu yêu cầu kết nối và sẵn sàng đồng bộ.',
    'shareQrLink': 'Chia sẻ mã QR',
    'shareQrSubject': 'Kết nối với tôi trên NexBook',
    'cannotLoadQr': 'Không thể tải mã QR của bạn.',
    'account': 'Tài khoản',
    'couldNotLoadAccount': 'Không thể tải thông tin tài khoản.',
    'preferences': 'Tùy chọn',
    'notifications': 'Thông báo',
    'notificationsHint': 'Thông báo kết nối và cập nhật hồ sơ',
    'automaticSync': 'Tự động đồng bộ',
    'automaticSyncHint': 'Đồng bộ dữ liệu mã hóa khi có mạng',
    'theme': 'Giao diện',
    'language': 'Ngôn ngữ',
    'yourData': 'Dữ liệu của bạn',
    'exportBackup': 'Xuất bản sao lưu',
    'exportBackupHint': 'Hồ sơ chính và cài đặt ở định dạng JSON',
    'importBackup': 'Nhập bản sao lưu',
    'importBackupHint': 'Khôi phục từ tệp JSON NexBook',
    'changePassword': 'Đổi mật khẩu',
    'signOut': 'Đăng xuất',
    'deleteAccount': 'Xóa tài khoản',
    'privacyNotice':
        'Nội dung hồ sơ được mã hóa trên thiết bị trước khi tải lên. Máy chủ NexBook không thể đọc dữ liệu này.',
    'backupSubject': 'Bản sao lưu mã hóa NexBook',
    'pasteBackupJson': 'Dán nội dung JSON sao lưu',
    'invalidBackup': 'Bản sao lưu không hợp lệ hoặc không được hỗ trợ.',
    'deleteAccountQuestion': 'Xóa tài khoản vĩnh viễn?',
    'deleteAccountWarning':
        'Tài khoản, kết nối, dữ liệu mã hóa, khóa thiết bị và dữ liệu cục bộ sẽ bị xóa. Không thể hoàn tác.',
    'currentPassword': 'Mật khẩu hiện tại',
    'newPasswordMin': 'Mật khẩu mới (từ 10 ký tự)',
    'changeRecoveryEmail': 'Đổi email khôi phục',
    'recoveryEmailUpdated': 'Đã cập nhật email khôi phục.',
    'theme.system': 'Theo hệ thống',
    'theme.light': 'Sáng',
    'theme.dark': 'Tối',
    'language.en': 'Tiếng Anh',
    'language.vi': 'Tiếng Việt',
    'language.zh': 'Tiếng Trung',
    'language.ja': 'Tiếng Nhật',
    'defaultProfile.family': 'Gia đình',
    'defaultProfile.friends': 'Bạn bè',
    'defaultProfile.work': 'Công việc',
    'defaultProfile.public': 'Công khai',
    'field.fullName': 'Họ và tên',
    'field.nickname': 'Biệt danh',
    'field.birthday': 'Ngày sinh',
    'field.gender': 'Giới tính',
    'field.company': 'Công ty',
    'field.position': 'Chức vụ',
    'field.phone': 'Số điện thoại',
    'field.email': 'Email',
    'field.address': 'Địa chỉ',
    'field.website': 'Trang web',
    'field.facebook': 'Facebook',
    'field.instagram': 'Instagram',
    'field.linkedIn': 'LinkedIn',
    'field.telegram': 'Telegram',
    'field.whatsApp': 'WhatsApp',
    'field.weChat': 'WeChat',
    'field.zalo': 'Zalo',
    'field.github': 'GitHub',
    'field.notes': 'Ghi chú',
    'error.passwordMismatch': 'Hai mật khẩu không trùng khớp.',
    'error.weakPassword': 'Mật khẩu phải có ít nhất 10 ký tự.',
    'error.invalidUsername':
        'Tên đăng nhập phải có 3–32 ký tự và chỉ gồm chữ, số, dấu chấm hoặc gạch dưới.',
    'error.invalidEmail': 'Hãy nhập đúng địa chỉ email khôi phục.',
    'error.usernameRequired': 'Hãy nhập tên đăng nhập.',
    'error.usernameExists': 'Tên đăng nhập này đã được sử dụng.',
    'error.recoveryEmailExists':
        'Email khôi phục này đã liên kết với tài khoản khác.',
    'error.invalidCredentials': 'Tên đăng nhập hoặc mật khẩu không đúng.',
    'error.invalidPassword': 'Mật khẩu hiện tại không đúng.',
    'error.invalidToken': 'Mã đặt lại mật khẩu không đúng hoặc đã hết hạn.',
    'error.accountDisabled': 'Tài khoản này đã bị vô hiệu hóa.',
    'error.unauthorized': 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
    'error.connectionExists':
        'Bạn đã kết nối hoặc đang có yêu cầu chờ với người này.',
    'error.invalidPeer': 'Bạn không thể tự kết nối với chính mình.',
    'error.invalidProfileSet':
        'Hồ sơ chia sẻ này chưa sẵn sàng. Hãy đồng bộ rồi thử lại.',
    'error.invalidState':
        'Không thể thực hiện thao tác này ở trạng thái hiện tại.',
    'error.forbidden': 'Bạn không có quyền thực hiện thao tác này.',
    'error.versionConflict':
        'Dữ liệu đã thay đổi ở nơi khác. Hãy đồng bộ rồi thử lại.',
    'error.rateLimited':
        'Bạn thao tác quá nhanh. Vui lòng chờ một lúc rồi thử lại.',
    'error.network':
        'Không thể kết nối tới NexBook. Hãy kiểm tra mạng rồi thử lại.',
    'error.timeout': 'Yêu cầu mất quá nhiều thời gian. Vui lòng thử lại.',
    'error.server': 'NexBook đang tạm thời gián đoạn. Vui lòng thử lại sau.',
    'error.generic': 'Đã xảy ra lỗi. Vui lòng thử lại.',
  },
  'zh': {
    'tagline': '您的联系人，您的密钥。',
    'username': '用户名',
    'usernameHint': '3–32 个字符：字母、数字、句点或下划线',
    'legacyLoginHint': '旧账户暂时可以使用邮箱登录',
    'recoveryEmail': '恢复邮箱',
    'recoveryEmailHint': '仅在忘记密码时使用',
    'passwordMin': '密码（至少 10 个字符）',
    'reenterPassword': '再次输入密码',
    'createAccount': '创建账户',
    'accountCreatedSignIn': '账户已创建，请登录以继续。',
    'signIn': '登录',
    'forgotPassword': '忘记密码？',
    'alreadyHaveAccount': '已有账户？',
    'createAnAccount': '创建账户',
    'resetToken': '密码重置码',
    'newPassword': '新密码',
    'cancel': '取消',
    'continue': '继续',
    'save': '保存',
    'delete': '删除',
    'change': '更改',
    'import': '导入',
    'profile': '个人资料',
    'contacts': '联系人',
    'connections': '连接',
    'qr': '二维码',
    'myQr': '我的二维码',
    'settings': '设置',
    'scan': '扫描',
    'searchContacts': '搜索姓名、昵称或公司',
    'noContacts': '暂无联系人。扫描 NexBook 二维码即可连接。',
    'privateContact': '私密联系人',
    'connectionRequest': '连接请求 · {id}',
    'incomingRequests': '收到的请求',
    'sentRequests': '已发送',
    'incomingRequest': '希望与您连接',
    'sentRequest': '等待对方回应',
    'noConnectionRequests': '没有待处理的连接请求。',
    'accept': '接受',
    'reject': '拒绝',
    'cancelRequest': '取消请求',
    'changeSharingProfile': '更改共享资料',
    'disable': '停用',
    'enable': '启用',
    'offlineCacheUnavailable': '无法读取离线数据。',
    'shareWhichProfile': '要共享哪个资料？',
    'myProfile': '我的资料',
    'syncNow': '立即同步',
    'addYourDetails': '添加您的信息',
    'fieldsSaved': '已在本机保存 {count} 个字段',
    'sharingProfiles': '共享资料',
    'sharingProfilesHint': '每份资料都会单独加密，仅包含您选择的字段。',
    'visibleFieldsVersion': '{count} 个可见字段 · 版本 {version}',
    'duplicate': '复制',
    'copySuffix': '{name} 副本',
    'profilesSynced': '加密资料已同步。',
    'syncQueued': '网络恢复后将自动重试同步。',
    'masterProfile': '主资料',
    'saveLocally': '保存到本机',
    'newSharingProfile': '新建共享资料',
    'editSharingProfile': '编辑共享资料',
    'name': '名称',
    'scanQr': '扫描 NexBook 二维码',
    'saveQr': '保存二维码',
    'shareQr': '分享二维码',
    'uploadQrImage': '选择二维码图片',
    'toggleFlash': '切换闪光灯',
    'switchCamera': '切换摄像头',
    'qrSaved': '二维码图片已保存。',
    'qrNotFound': '此图片中未找到 NexBook 二维码。',
    'connectionQueued': '连接请求已保存，等待同步。',
    'shareQrLink': '共享二维码',
    'shareQrSubject': '在 NexBook 上与我连接',
    'cannotLoadQr': '无法加载您的二维码。',
    'account': '账户',
    'couldNotLoadAccount': '无法加载账户信息。',
    'preferences': '偏好设置',
    'notifications': '通知',
    'notificationsHint': '连接和资料更新提醒',
    'automaticSync': '自动同步',
    'automaticSyncHint': '联网时同步加密更改',
    'theme': '主题',
    'language': '语言',
    'yourData': '您的数据',
    'exportBackup': '导出备份',
    'exportBackupHint': '以 JSON 格式导出主资料和设置',
    'importBackup': '导入备份',
    'importBackupHint': '从 NexBook JSON 恢复',
    'changePassword': '更改密码',
    'signOut': '退出登录',
    'deleteAccount': '删除账户',
    'privacyNotice': '资料内容在上传前会在此设备上加密，NexBook 服务器无法读取。',
    'backupSubject': 'NexBook 加密设备备份',
    'pasteBackupJson': '粘贴备份 JSON',
    'invalidBackup': '此备份无效或不受支持。',
    'deleteAccountQuestion': '永久删除账户？',
    'deleteAccountWarning': '您的账户、连接、加密数据、设备密钥和本地数据都将被删除，且无法恢复。',
    'currentPassword': '当前密码',
    'newPasswordMin': '新密码（至少 10 个字符）',
    'changeRecoveryEmail': '更改恢复邮箱',
    'recoveryEmailUpdated': '恢复邮箱已更新。',
    'theme.system': '跟随系统',
    'theme.light': '浅色',
    'theme.dark': '深色',
    'language.en': '英语',
    'language.vi': '越南语',
    'language.zh': '中文',
    'language.ja': '日语',
    'defaultProfile.family': '家人',
    'defaultProfile.friends': '朋友',
    'defaultProfile.work': '工作',
    'defaultProfile.public': '公开',
    'field.fullName': '姓名',
    'field.nickname': '昵称',
    'field.birthday': '生日',
    'field.gender': '性别',
    'field.company': '公司',
    'field.position': '职位',
    'field.phone': '电话',
    'field.email': '邮箱',
    'field.address': '地址',
    'field.website': '网站',
    'field.facebook': 'Facebook',
    'field.instagram': 'Instagram',
    'field.linkedIn': 'LinkedIn',
    'field.telegram': 'Telegram',
    'field.whatsApp': 'WhatsApp',
    'field.weChat': '微信',
    'field.zalo': 'Zalo',
    'field.github': 'GitHub',
    'field.notes': '备注',
    'error.passwordMismatch': '两次输入的密码不一致。',
    'error.weakPassword': '密码必须至少包含 10 个字符。',
    'error.invalidUsername': '用户名必须为 3–32 个字符，且只能包含字母、数字、句点或下划线。',
    'error.invalidEmail': '请输入有效的恢复邮箱。',
    'error.usernameRequired': '请输入用户名。',
    'error.usernameExists': '此用户名已被使用。',
    'error.recoveryEmailExists': '此恢复邮箱已关联其他账户。',
    'error.invalidCredentials': '用户名或密码不正确。',
    'error.invalidPassword': '当前密码不正确。',
    'error.invalidToken': '重置码无效或已过期。',
    'error.accountDisabled': '此账户已被停用。',
    'error.unauthorized': '登录会话已过期，请重新登录。',
    'error.connectionExists': '您已与此人连接，或已有待处理请求。',
    'error.invalidPeer': '您无法与自己的账户连接。',
    'error.invalidProfileSet': '此共享资料不可用，请同步后重试。',
    'error.invalidState': '当前状态下无法执行此操作。',
    'error.forbidden': '您无权执行此操作。',
    'error.versionConflict': '数据已在其他位置更改，请同步后重试。',
    'error.rateLimited': '请求过于频繁，请稍后重试。',
    'error.network': '无法连接 NexBook，请检查网络后重试。',
    'error.timeout': '请求超时，请重试。',
    'error.server': 'NexBook 暂时不可用，请稍后重试。',
    'error.generic': '发生错误，请重试。',
  },
  'ja': {
    'tagline': 'あなたの連絡先。あなたの鍵。',
    'username': 'ユーザー名',
    'usernameHint': '3～32文字：英数字、ピリオド、アンダースコア',
    'legacyLoginHint': '旧アカウントは一時的にメールでもログインできます',
    'recoveryEmail': '復旧用メールアドレス',
    'recoveryEmailHint': 'パスワードを忘れた場合にのみ使用します',
    'passwordMin': 'パスワード（10文字以上）',
    'reenterPassword': 'パスワードを再入力',
    'createAccount': 'アカウントを作成',
    'accountCreatedSignIn': 'アカウントを作成しました。ログインしてください。',
    'signIn': 'ログイン',
    'forgotPassword': 'パスワードをお忘れですか？',
    'alreadyHaveAccount': 'アカウントをお持ちですか？',
    'createAnAccount': 'アカウントを作成',
    'resetToken': 'パスワード再設定コード',
    'newPassword': '新しいパスワード',
    'cancel': 'キャンセル',
    'continue': '続行',
    'save': '保存',
    'delete': '削除',
    'change': '変更',
    'import': 'インポート',
    'profile': 'プロフィール',
    'contacts': '連絡先',
    'connections': '接続',
    'qr': 'QR',
    'myQr': '自分のQR',
    'settings': '設定',
    'scan': 'スキャン',
    'searchContacts': '名前、ニックネーム、会社を検索',
    'noContacts': '連絡先がありません。NexBookのQRコードをスキャンして接続してください。',
    'privateContact': '非公開の連絡先',
    'connectionRequest': '接続リクエスト · {id}',
    'incomingRequests': '受信したリクエスト',
    'sentRequests': '送信済み',
    'incomingRequest': 'あなたとの接続を希望しています',
    'sentRequest': '応答を待っています',
    'noConnectionRequests': '保留中の接続リクエストはありません。',
    'accept': '承認',
    'reject': '拒否',
    'cancelRequest': 'リクエストを取り消す',
    'changeSharingProfile': '共有プロフィールを変更',
    'disable': '無効にする',
    'enable': '有効にする',
    'offlineCacheUnavailable': 'オフラインデータを読み込めません。',
    'shareWhichProfile': 'どのプロフィールを共有しますか？',
    'myProfile': '自分のプロフィール',
    'syncNow': '今すぐ同期',
    'addYourDetails': '情報を追加',
    'fieldsSaved': '{count}項目を端末に保存済み',
    'sharingProfiles': '共有プロフィール',
    'sharingProfilesHint': '各プロフィールは個別に暗号化され、選択した項目だけが含まれます。',
    'visibleFieldsVersion': '表示項目 {count}件 · バージョン{version}',
    'duplicate': '複製',
    'copySuffix': '{name} のコピー',
    'profilesSynced': '暗号化プロフィールを同期しました。',
    'syncQueued': '接続が回復したら同期を再試行します。',
    'masterProfile': 'メインプロフィール',
    'saveLocally': '端末に保存',
    'newSharingProfile': '共有プロフィールを作成',
    'editSharingProfile': '共有プロフィールを編集',
    'name': '名前',
    'scanQr': 'NexBook QRをスキャン',
    'saveQr': 'QRを保存',
    'shareQr': 'QRを共有',
    'uploadQrImage': 'QR画像を選択',
    'toggleFlash': 'ライトを切り替え',
    'switchCamera': 'カメラを切り替え',
    'qrSaved': 'QR画像を保存しました。',
    'qrNotFound': 'この画像にNexBook QRが見つかりません。',
    'connectionQueued': '接続リクエストを保存し、同期待ちにしました。',
    'shareQrLink': 'QRコードを共有',
    'shareQrSubject': 'NexBookでつながる',
    'cannotLoadQr': 'QRコードを読み込めません。',
    'account': 'アカウント',
    'couldNotLoadAccount': 'アカウント情報を読み込めません。',
    'preferences': '環境設定',
    'notifications': '通知',
    'notificationsHint': '接続とプロフィール更新のお知らせ',
    'automaticSync': '自動同期',
    'automaticSyncHint': 'オンライン時に暗号化された変更を同期',
    'theme': 'テーマ',
    'language': '言語',
    'yourData': 'あなたのデータ',
    'exportBackup': 'バックアップをエクスポート',
    'exportBackupHint': 'メインプロフィールと設定をJSONで保存',
    'importBackup': 'バックアップをインポート',
    'importBackupHint': 'NexBook JSONから復元',
    'changePassword': 'パスワードを変更',
    'signOut': 'ログアウト',
    'deleteAccount': 'アカウントを削除',
    'privacyNotice': 'プロフィールはアップロード前に端末上で暗号化されます。NexBookのサーバーは内容を読み取れません。',
    'backupSubject': 'NexBook暗号化端末バックアップ',
    'pasteBackupJson': 'バックアップJSONを貼り付け',
    'invalidBackup': 'このバックアップは無効、または対応していません。',
    'deleteAccountQuestion': 'アカウントを完全に削除しますか？',
    'deleteAccountWarning': 'アカウント、接続、暗号化データ、端末キー、ローカルデータが削除されます。この操作は元に戻せません。',
    'currentPassword': '現在のパスワード',
    'newPasswordMin': '新しいパスワード（10文字以上）',
    'changeRecoveryEmail': '復旧用メールアドレスを変更',
    'recoveryEmailUpdated': '復旧用メールアドレスを更新しました。',
    'theme.system': 'システム設定',
    'theme.light': 'ライト',
    'theme.dark': 'ダーク',
    'language.en': '英語',
    'language.vi': 'ベトナム語',
    'language.zh': '中国語',
    'language.ja': '日本語',
    'defaultProfile.family': '家族',
    'defaultProfile.friends': '友人',
    'defaultProfile.work': '仕事',
    'defaultProfile.public': '公開',
    'field.fullName': '氏名',
    'field.nickname': 'ニックネーム',
    'field.birthday': '誕生日',
    'field.gender': '性別',
    'field.company': '会社',
    'field.position': '役職',
    'field.phone': '電話番号',
    'field.email': 'メール',
    'field.address': '住所',
    'field.website': 'ウェブサイト',
    'field.facebook': 'Facebook',
    'field.instagram': 'Instagram',
    'field.linkedIn': 'LinkedIn',
    'field.telegram': 'Telegram',
    'field.whatsApp': 'WhatsApp',
    'field.weChat': 'WeChat',
    'field.zalo': 'Zalo',
    'field.github': 'GitHub',
    'field.notes': 'メモ',
    'error.passwordMismatch': 'パスワードが一致しません。',
    'error.weakPassword': 'パスワードは10文字以上で入力してください。',
    'error.invalidUsername': 'ユーザー名は3～32文字で、英数字、ピリオド、アンダースコアのみ使用できます。',
    'error.invalidEmail': '有効な復旧用メールアドレスを入力してください。',
    'error.usernameRequired': 'ユーザー名を入力してください。',
    'error.usernameExists': 'このユーザー名はすでに使用されています。',
    'error.recoveryEmailExists': 'この復旧用メールアドレスは別のアカウントに登録されています。',
    'error.invalidCredentials': 'ユーザー名またはパスワードが正しくありません。',
    'error.invalidPassword': '現在のパスワードが正しくありません。',
    'error.invalidToken': '再設定コードが無効、または期限切れです。',
    'error.accountDisabled': 'このアカウントは無効化されています。',
    'error.unauthorized': 'ログインの有効期限が切れました。再度ログインしてください。',
    'error.connectionExists': 'この相手とは接続済み、または保留中のリクエストがあります。',
    'error.invalidPeer': '自分自身のアカウントには接続できません。',
    'error.invalidProfileSet': 'この共有プロフィールは利用できません。同期してから再試行してください。',
    'error.invalidState': '現在の状態ではこの操作を実行できません。',
    'error.forbidden': 'この操作を行う権限がありません。',
    'error.versionConflict': '別の場所でデータが変更されました。同期してから再試行してください。',
    'error.rateLimited': 'リクエストが多すぎます。しばらく待ってから再試行してください。',
    'error.network': 'NexBookに接続できません。ネットワークを確認して再試行してください。',
    'error.timeout': 'リクエストがタイムアウトしました。再試行してください。',
    'error.server': 'NexBookは一時的に利用できません。後でもう一度お試しください。',
    'error.generic': 'エラーが発生しました。もう一度お試しください。',
  },
};
